ForceTorqueThresholds nominal_thresholds # Thresholds during constant velocity movement phases
ForceTorqueThresholds acceleration_thresholds # Thresholds during acceleration/deceleration
---
bool success
string error
