# The mass of the object
float64 mass
# Position of the center of mass
float64[3] center_of_mass
# Inertia of the object - the provided 3x3 matrix is in column major form.
float64[9] load_inertia
---
bool success
string error

