# Sets the transformation matrix describing the stiffness frame relative to the TCP frame.
# A 4x4 column-major transformation matrix representing the position and orientation.
float64[16] transformation
---
bool success
string error
